language: groovy
matrix:
  include:
  - jdk: openjdk7
  - jdk: oraclejdk9
  - jdk: oraclejdk8
    env: TEST_ALL_CONTAINERS="['jetty7']"
  - jdk: oraclejdk8
    env: TEST_ALL_CONTAINERS="['jetty8']"
  - jdk: oraclejdk8
    env: TEST_ALL_CONTAINERS="['jetty9']"
  - jdk: oraclejdk8
    env: TEST_ALL_CONTAINERS="['tomcat7']"
  - jdk: oraclejdk8
    env: TEST_ALL_CONTAINERS="['tomcat8']"
  - jdk: oraclejdk8
    env: TEST_ALL_CONTAINERS="['tomcat85']"
  - jdk: oraclejdk8
    env: TEST_ALL_CONTAINERS="['tomcat9']"
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches
    - $HOME/.gradle/wrapper
before_install:
  - chmod +x gradlew
  - sudo apt-get -qq update
  - sudo apt-get install -y zip curl locate libbcprov-java
  - |
    sudo ln -s /usr/share/java/bcprov.jar /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/ext/bcprov.jar \
    && sudo awk -F . -v OFS=. 'BEGIN{n=2}/^security\.provider/ {split($3, posAndEquals, "=");$3=n++"="posAndEquals[2];print;next} 1' /etc/java-7-openjdk/security/java.security > /tmp/java.security \
    && sudo echo "security.provider.1=org.bouncycastle.jce.provider.BouncyCastleProvider" >> /tmp/java.security \
    && sudo mv /tmp/java.security /etc/java-7-openjdk/security/java.security
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
install:
  - true
script:
  - |
    if [[ "${TRAVIS_JDK_VERSION}" == "oraclejdk8" && ( "${TRAVIS_BRANCH}" == "master" || "${TRAVIS_BRANCH}" == "gretty-2.x" || "${TRAVIS_EVENT_TYPE}" == "pull_request" || "${TRAVIS_EVENT_TYPE}" == "cron" ) ]]; then
      ./gradlew -PgeckoDriverPlatform=linux64 -PgeckoDriverVersion=0.20.0 -PtestAllContainers=${TEST_ALL_CONTAINERS} build testAll
    else
      ./gradlew build
    fi
env:
  global:
    - secure: "yP1LR0IRe1CHjKKq21bAxTU/lLTFjmtx0Gaem0Ttl0HTvK72cyZQ3zs1VgGZfnsqjtDmT0KCipk7j0/S6kf4TxLE8esXT3t9twRO2hTpBO0AhJmvgiaLtOkrQx68I+LamUpVpkYod69yhvVHjJxxoBM8h6EgxricLD0cboO8l/hLFdBODHkUs+07olQyeiuXJ5xgdviC7jmEO5XhdIb2kVfXmdcCHAjw3ow4h/02gw0F6gt0fsPxNlaLqWr1hnmop1bcRJ02llBBf4odd7IZHYBtclrfYrKB1ID6VOra0QscEbTuCcZaSNCNPzt/xMuyOCDFZlKCatYpXo+lDqTASa8Np+Ck9yBpbcBED3NGyadbv9ASbKZOHc65n9drINSzcX3w50MaELxeypNMjQ9W9KghXKdCtAwTVe2OmzOS283OmBGz8PNOI1/t3+rYfqE5SkPiQDSRfJtiZqHDEu7TrxfdoumDQPw/znvtcW2MPrCQpxCnKhseT3EJ1SNJVGFzkcbyAfs90uW/fyWYVNhcfP4LgM4gDy4Ggh/5PTEAXQ9BWvVJ4fSCkZfgMriS9MmgI7054V/PgmZN1Io2UmYK3Nw77u3OpYr4Uz1PlMsWE5ilB09+pDeUZmDLzSF19Z8UV8wRsafYFaO8e9wK0aCtUHfxAbtbpF4daJxqT6+7LVw="
    - secure: "XvfP1aard+wx4ZcMkfkwOOztmPjHhOoCbtjztVxrNY8rM85CVbeOVDqRgpgs8G0oj+N/9pv1q3yJkSzcl3P61Y/lyq/emZlCB3A9byQETY+8uvmuT8+uh5/N6nKTmQlXooAaSmLtEdXs9XZq8VZ56zBYS7JsqSmlvGUVl37hHU9rSAD5x8Rsb5SisYbvsanhu/qjpAojnBRVvi7hW61U5NWJThKnijUQ1LaY1rRSCbEmXvGzG1rt/RPMhlq11vc+HgArW6dJISZ+6na9Lt2c0clyu0a/WXPXORWhkuClzV+2C4qsilkyTixni+McI4PaMVV9ZoVq951WGxy+iiv2rsh5ANJjFcv/jxSxUsdaLCGwPFny85YJoon+dDocyf4zGjLg58dHwHbmYpwMmQp6L3jeDcxJXXK9pveM1aShFUWKd/+Xgu4lltSuWO1G+CWfG8lzP7kFGcHvxMD86WdUBFoXyBoiiwETauHA8mXVd72Kp+6/8BqxiaZiXPD/7m0q+3Qtl2v+r3GXr8bg/ARuEigts1vdjxybnHJJG4nGsz4NKU6XiGKMMwB45RFwJ0qeeXKZrGjtt8d9pTkwvjd6chnx4LTswl7rgbjlr5RNyHS53TnCraUfEwabO+tJjCurrO1zKFuhWoYJhHZryLMTeGaX/3GdIaVJEP9YKkBVHNk="
    - JAVA_OPTS="-XX:PermSize=512M -XX:MaxPermSize=1G"

deploy:
  - provider: script
    skip_cleanup: true
    script: ./gradlew artifactoryPublish -PbintrayUser=${BINTRAY_USER} -PbintrayKey=${BINTRAY_KEY} -PbintrayRepo=${BINTRAY_REPO} -PbintrayPackage=${BINTRAY_PACKAGE}
    on:
      repo: gretty-gradle-plugin/gretty
      branch: master
      jdk: oraclejdk8
      condition: $TEST_ALL_CONTAINERS =~ "jetty9.4'"
  - provider: script
    skip_cleanup: true
    script: ./gradlew artifactoryPublish -PbintrayUser=${BINTRAY_USER} -PbintrayKey=${BINTRAY_KEY} -PbintrayRepo=${BINTRAY_REPO} -PbintrayPackage=${BINTRAY_PACKAGE}
    on:
      repo: gretty-gradle-plugin/gretty
      branch: gretty-2.x
      jdk: oraclejdk8
      condition: $TEST_ALL_CONTAINERS =~ "jetty9'"
